version: '3.9'

services:
  django:
    image: my_django_img
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_vol:/home/app/web/static
  nginx:
    build:
      context: ./nginx
    ports: 
      - 80:80
    depends_on:
      - django
    volumes:
      - static_vol:/home/app/web/static

volumes:
  static_vol: